### ISSUE TITLE
Raw images fail to appear

### ISSUE THREAD

**Issue by gejoreni** [u12206050/figma-plugin-graphql#2]
It appears that when a query returns raw images without an extension it fails to display the content properly. It seems somewhat hit or miss - one will duplicate and then it will clone itself and stop. Great plugin tho!

**Comment by gejoreni** [comment]
here is the data that I'm iterating

`{
  "data": {
    "listings": [
      {
        "activity": {
          "title": "Stock Market Investing Game!  Beginners Will Learn to Pick Winners with $100K virtual $.  Ages  9-13",
          "summary": "Learn what a stock is and how to pick great stocks to invest in.  Then get $100K in virtual cash to trade stocks in a simulation game that uses real-time stock prices. ** Check meeting dates of each section as course format varies!!",
          "details": {
            "photo": "https://cdn.filestackcontent.com/vhYlMwrETWrBd2E0gBN2"
          },
          "leader": {
            "uid": "2f1290a9-f1c5-465e-aa11-1d4f914bdccc",
            "name": "Lisa Kornberg",
            "photo": "https://cdn.filestackcontent.com/UsxayLfPQMmPSXpa5fsk",
            "averageActivityStarRating": 4.883720930232558,
            "reviewCount": 559
          }
        }
      },
      {
        "activity": {
          "title": "How To Make Awesome Animated Movies (Intro to Animation)",
          "summary": "This course is an introduction to 2D animation. Students will go from having no knowledge of animation to having made their very own short animated film. ",
          "details": {
            "photo": "https://cdn.filestackcontent.com/43OzWeccRYu3tkusNRAW"
          },
          "leader": {
            "uid": "6e20209a-81c6-42d2-9ef8-b48a29c75e37",
            "name": "Cody Zervas",
            "photo": "https://cdn.filestackcontent.com/F3EJ8CfPTH6XgFtECdgl",
            "averageActivityStarRating": 4.83089430894309,
            "reviewCount": 615
          }
        }
      },
      {
        "activity": {
          "title": "Beginner Reading-From Phonics to Fluency",
          "summary": "Systematic, evidence-based phonics instruction reinforcing phonological and phonemic awareness to achieve success in reading",
          "details": {
            "photo": "https://cdn.filestackcontent.com/xaZIE9x8TB2DGBxiwI6l"
          },
          "leader": {
            "uid": "3f6be72c-4fa5-47d9-89f3-ec877a68af69",
            "name": "Katharine H.",
            "photo": "https://cdn.filestackcontent.com/hWuwZmJPQCK8POTDmkmP",
            "averageActivityStarRating": 4.959183673469388,
            "reviewCount": 294
          }
        }
      },
      {
        "activity": {
          "title": "Wings of Fire - Fanfiction Camp",
          "summary": "A week of dragon creating, writing, and discussion!",
          "details": {
            "photo": "https://cdn.filestackcontent.com/XqLWYPGaRkGbrz8Uae4s"
          },
          "leader": {
            "uid": "d9fcdca3-ff49-4018-9cf9-7c400f7c3cb7",
            "name": "Jackson Pearce",
            "photo": "https://cdn.filestackcontent.com/C03GTdSlS8iOaJfv7tAc",
            "averageActivityStarRating": 4.91937069813176,
            "reviewCount": 1017
          }
        }
      },
      {
        "activity": {
          "title": "Flexible Schedule: Smartest Artists: Art Class With A Touch of History, Math, Lit and Science",
          "summary": "\"Every Child is an Artist\" ~ Pablo Picasso In this semester long art class, children will learn new art techniques and create a masterpiece every week. We will also tie in science, history, math or literature to every art lesson! *Ask about sibling discounts!*",
          "details": {
            "photo": "https://cdn.filestackcontent.com/NItQnR8QHiZ2vXzUqXUt"
          },
          "leader": {
            "uid": "8fab59b0-3efe-4304-a07c-0e2f279b3ebe",
            "name": "Kristen Cwynar",
            "photo": "https://cdn.filestackcontent.com/JVUAx9PaScKfInccObiG",
            "averageActivityStarRating": 4.902796271637817,
            "reviewCount": 751
          }
        }
      },
      {
        "activity": {
          "title": "STEM CL1D: Electrical Circuits Level 1 - Learn with Snap Circuits! (5-Day-Camp)",
          "summary": "How do circuits work?? In this 5-day course, we learn the fundamentals of circuits through the use of Snap Circuits (the Lego of electronics!) We will do fun projects while engaging students in science and technology.",
          "details": {
            "photo": "https://cdn.filestackcontent.com/aK0455lnQESWdht5v87F"
          },
          "leader": {
            "uid": "cee52ce1-c33e-4fc9-9b4f-a22c1f94cc57",
            "name": "J. Galindo",
            "photo": "https://cdn.filestackcontent.com/U5MclRAyTpGj0fb8SHQ1",
            "averageActivityStarRating": 4.952815829528158,
            "reviewCount": 1314
          }
        }
      },
      {
        "activity": {
          "title": "Metrocraft: Our Class Creates and Governs a Minecraft City!",
          "summary": "Economics, civics and social studies in a virtual Minecraft-type World",
          "details": {
            "photo": "https://cdn.filestackcontent.com/CdQ2xtLrTzykLzvCeHu9"
          },
          "leader": {
            "uid": "99250a97-5055-4349-a440-77445f734215",
            "name": "Right Brain Curriculum",
            "photo": "https://cdn.filestackcontent.com/4LaLAk39ReysiaMjXT47",
            "averageActivityStarRating": 4.913366336633663,
            "reviewCount": 404
          }
        }
      },
      {
        "activity": {
          "title": "Black History From a Decolonized Perspective (African American History) ",
          "summary": "In this 8 week course students will learn about black history beginning with Ancient African kingdoms and societies. ",
          "details": {
            "photo": "https://cdn.filestackcontent.com/hCA3gbjSmmGBEkbJw7ON"
          },
          "leader": {
            "uid": "2b36148b-2df2-4be3-ba2f-1d503eeab096",
            "name": "Kind Academy by Iman Alleyne",
            "photo": "https://cdn.filestackcontent.com/haXcjyZiR5iJ23AD1s3Q",
            "averageActivityStarRating": 4.863247863247864,
            "reviewCount": 234
          }
        }
      },
      {
        "activity": {
          "title": "Learn to Debate - Introductory Argumentation in 5 Classes",
          "summary": "In this five session long course, students will learn about the basics of debate, develop some advanced skills, and participate in a mini-tournament.",
          "details": {
            "photo": "https://cdn.filestackcontent.com/GwYRjFteRMWNF0hI8Ano"
          },
          "leader": {
            "uid": "c32032e9-93cb-48eb-b728-62e1d9c9867f",
            "name": "Broome County Debate Alliance",
            "photo": "https://cdn.filestackcontent.com/LrvmbbcwSwuWiVKsTlhs",
            "averageActivityStarRating": 4.723858615611193,
            "reviewCount": 1358
          }
        }
      },
      {
        "activity": {
          "title": "Beginning Multiplication Facts Made Easy!",
          "summary": "This course is designed to help students learn their multiplication facts 0 through 12 by means of patterns, rules, and mnemonic devices. ",
          "details": {
            "photo": "https://cdn.filestackcontent.com/Z1WcRb4RsBHeNEZvL9xg"
          },
          "leader": {
            "uid": "c3d53aba-e728-43c0-b4e4-46fa5ef88ee8",
            "name": " Michaela Sellers, M.Ed. ",
            "photo": "https://cdn.filestackcontent.com/X3A2OMbYTI6cluXJlDR8",
            "averageActivityStarRating": 4.887850467289719,
            "reviewCount": 1177
          }
        }
      }
    ]
  }
}`

**Comment by u12206050** [comment]
Hmm, do you know if Figma handles raw images differently than normal ones?
I haven't worked with raw images in Figma.

**Comment by gejoreni** [comment]
I don't know. It seems to sort of work sometimes and then fails others. One
time I clicked it, it generated 10 new cards but couldn't make it work
again. I think they're just jpeg? But they don't have extensions from
filestack.

**Comment by u12206050** [comment]
I am unfortunately unable to reproduce this issue. Images without extension seem to work all the time.

**Comment by gejoreni** [comment]
I think it's an issue of format. It's possible those images are webp or
another invalid format. I was able to fix this issue on the json by adding
a format change thru filestack:  https://cdn.filestackcontent.com/
*output=format:png*/aK0455lnQESWdht5v87F

The issue is - I am unable to modify the return with the plugin. A feature
request would be to provide a way to modify a $value with javascript - lots
of reasons this would be useful.
Thanks.
